# Generated by Django 5.0.4 on 2024-04-25 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='User Token'),
        ),
    ]
