# Generated by Django 5.0.4 on 2024-05-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('title', models.CharField(max_length=255, verbose_name='Name of the course')),
                ('description', models.TextField(blank=True, verbose_name='Course description')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is the course visible in the system')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
