# Generated by Django 5.0.4 on 2024-05-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('rating', models.PositiveSmallIntegerField(default=1, verbose_name='Rating')),
                ('text', models.TextField(blank=True, default='', verbose_name='Review text')),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='courses.course', verbose_name='Course')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='members.member', verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Course review',
                'verbose_name_plural': 'Course reviews',
                'unique_together': {('member', 'course')},
            },
        ),
    ]
