# Generated by Django 5.0.4 on 2024-05-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursereview'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseReview',
            new_name='CourseReviewModel',
        ),
    ]
